/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter:3.1.3")
    api("org.springframework.boot:spring-boot-starter-web:3.1.3")
    api("org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:4.0.3")
    api("org.springframework.boot:spring-boot-starter-actuator:3.1.3")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:3.1.3")
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.1.3")
}

group = "com.telebet"
version = "0.0.1-SNAPSHOT"
description = "telegram-service"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
